
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUSCULAS = 5;
  public static final int VIRGUILILLA = 15;
  public static final int INTERROGACION = 19;
  public static final int GUION = 13;
  public static final int PUNTO = 16;
  public static final int SUMA = 17;
  public static final int SIGNOS_ASCII = 6;
  public static final int KLEENE = 20;
  public static final int DOS_PUNTOS = 11;
  public static final int PORCENTAJE = 8;
  public static final int LLAVE_CERRAR = 10;
  public static final int COMA = 14;
  public static final int MAYOR = 12;
  public static final int EOF = 0;
  public static final int CONJ = 3;
  public static final int DISYUNCION = 18;
  public static final int MAYUSCULAS = 4;
  public static final int error = 1;
  public static final int LLAVE_ABRIR = 9;
  public static final int ENTERO = 2;
  public static final int PUNTO_Y_COMA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "CONJ",
  "MAYUSCULAS",
  "MINUSCULAS",
  "SIGNOS_ASCII",
  "PUNTO_Y_COMA",
  "PORCENTAJE",
  "LLAVE_ABRIR",
  "LLAVE_CERRAR",
  "DOS_PUNTOS",
  "MAYOR",
  "GUION",
  "COMA",
  "VIRGUILILLA",
  "PUNTO",
  "SUMA",
  "DISYUNCION",
  "INTERROGACION",
  "KLEENE"
  };
}

